name: Automated Documentation

on:
  push:
    branches: [main, develop]
    paths:
      - 'docs/**'
      - 'packages/**/README.md'
      - 'README.md'
  pull_request:
    paths:
      - 'docs/**'
      - 'packages/**/README.md'
      - 'README.md'
  schedule:
    # Weekly documentation update
    - cron: '0 0 * * 1'

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate API documentation
        run: |
          # Generate TypeScript API docs
          npm run docs:api || echo "API docs generation not configured"

      - name: Generate code documentation
        run: |
          # Generate code documentation from comments
          npm run docs:code || echo "Code docs generation not configured"

      - name: Lint documentation
        run: |
          # Check documentation formatting
          npm run docs:lint || echo "Docs linting not configured"

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382954b84365f3d453
        with:
          name: documentation
          path: |
            docs/
            packages/*/README.md
            README.md
          retention-days: 30

  build-jekyll-site:
    name: Build Jekyll Site
    runs-on: ubuntu-latest
    needs: generate-docs
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Download documentation artifacts
        uses: actions/download-artifact@65a9edc5881444af0b9093e5e666db3dd7f06d4
        with:
          name: documentation
          path: docs-site

      - name: Setup Ruby
        uses: ruby/setup-ruby@8425965618f8b9a0c32f489d6b6c3b6b5c1239b
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Jekyll
        run: |
          gem install jekyll bundler
          cd docs-site
          bundle init
          echo 'gem "jekyll"' >> Gemfile
          echo 'gem "github-pages"' >> Gemfile
          bundle install

      - name: Build Jekyll site
        run: |
          cd docs-site
          bundle exec jekyll build --source docs --destination _site

      - name: Upload Jekyll site
        uses: actions/upload-artifact@65462800fd760344b1a7b4382954b84365f3d453
        with:
          name: jekyll-site
          path: docs-site/_site/
          retention-days: 30

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: build-jekyll-site
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Download Jekyll site
        uses: actions/download-artifact@65a9edc5881444af0b9093e5e666db3dd7f06d4
        with:
          name: jekyll-site
          path: docs-site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a284
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs-site
          cname: docs.noa-server.dev

  update-wiki:
    name: Update Wiki
    runs-on: ubuntu-latest
    needs: generate-docs
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout wiki
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download documentation artifacts
        uses: actions/download-artifact@65a9edc5881444af0b9093e5e666db3dd7f06d4
        with:
          name: documentation
          path: wiki-source

      - name: Sync documentation to wiki
        run: |
          cp -r wiki-source/* wiki/ || true
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated documentation update" || echo "No changes to commit"
          git push || echo "No changes to push"
