name: Deploy

on:
  push:
    tags:
      - "v*" # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch: # Allow manual deployment
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        type: choice
        options:
          - staging
          - production
      strategy:
        description: "Deployment strategy"
        required: true
        type: choice
        options:
          - standard
          - blue-green
          - canary

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "9.11.0"

jobs:
  pre-deployment-checks:
    name: Pre-Deployment Checks
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.determine-env.outputs.environment }}
      strategy: ${{ steps.determine-strategy.outputs.strategy }}

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@161b8d0c4739f28c4f8391fa2b2c23d8b6c4b2b2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Determine environment
        id: determine-env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi

      - name: Determine strategy
        id: determine-strategy
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "strategy=${{ github.event.inputs.strategy }}" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.determine-env.outputs.environment }}" == "production" ]]; then
            echo "strategy=blue-green" >> $GITHUB_OUTPUT
          else
            echo "strategy=standard" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm run lint

      - name: Run type checking
        run: pnpm run typecheck

      - name: Run security audit
        run: pnpm audit --audit-level=high || true

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: pre-deployment-checks

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: noa_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@161b8d0c4739f28c4f8391fa2b2c23d8b6c4b2b2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm run test:unit
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/noa_test
          REDIS_URL: redis://localhost:6379

      - name: Run integration tests
        run: pnpm run test:integration
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/noa_test
          REDIS_URL: redis://localhost:6379

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@0b7f87a49c3e4218e524ec8724b957a19cd1ec3a
        with:
          name: test-results
          path: coverage/

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@161b8d0c4739f28c4f8391fa2b2c23d8b6c4b2b2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run build:all

      - name: Upload build artifacts
        uses: actions/upload-artifact@0b7f87a49c3e4218e524ec8724b957a19cd1ec3a
        with:
          name: build-artifacts
          path: |
            packages/*/dist/
            node_modules/
          retention-days: 7

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [pre-deployment-checks, build]
    if: needs.pre-deployment-checks.outputs.environment == 'staging'
    environment:
      name: staging
      url: https://staging-api.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Download build artifacts
        uses: actions/download-artifact@65a9edc5881444af0b9093e5e666db3dd7f06d4
        with:
          name: build-artifacts

      - name: Deploy to staging
        run: |
          # Configure SSH or deployment method
          # Example: rsync, SCP, or deployment service
          echo "Deploying to staging..."

          # Run deployment script
          chmod +x scripts/deploy/deploy-staging.sh
          ./scripts/deploy/deploy-staging.sh ${{ needs.pre-deployment-checks.outputs.strategy }}
        env:
          DEPLOY_KEY: ${{ secrets.STAGING_DEPLOY_KEY }}

      - name: Send deployment notification
        if: always()
        uses: slackapi/slack-github-action@70cd7be8e40a46e8b612094aa26fbd48c5a13a8
        with:
          payload: |
            {
              "text": "Staging deployment ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Staging Deployment ${{ job.status }}*\nCommit: ${{ github.sha }}\nActor: ${{ github.actor }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [pre-deployment-checks, build]
    if: needs.pre-deployment-checks.outputs.environment == 'production'
    environment:
      name: production
      url: https://api.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Download build artifacts
        uses: actions/download-artifact@65a9edc5881444af0b9093e5e666db3dd7f06d4
        with:
          name: build-artifacts

      - name: Create pre-deployment backup
        run: |
          echo "Creating backup..."
          chmod +x scripts/deploy/backup-before-deploy.sh
          ./scripts/deploy/backup-before-deploy.sh production

      - name: Deploy to production
        run: |
          echo "Deploying to production..."

          # Run deployment script
          chmod +x scripts/deploy/deploy-production.sh
          AUTO_APPROVE=true ./scripts/deploy/deploy-production.sh ${{ needs.pre-deployment-checks.outputs.strategy }}
        env:
          DEPLOY_KEY: ${{ secrets.PRODUCTION_DEPLOY_KEY }}
          AUTO_APPROVE: "true"

      - name: Run health checks
        run: |
          echo "Running health checks..."
          chmod +x scripts/deploy/health-check.sh
          ./scripts/deploy/health-check.sh production

      - name: Monitor deployment
        run: |
          echo "Monitoring deployment..."
          chmod +x scripts/deploy/monitor-deployment.sh
          ./scripts/deploy/monitor-deployment.sh production 300

      - name: Rollback on failure
        if: failure()
        run: |
          echo "Deployment failed, rolling back..."
          chmod +x scripts/deploy/rollback.sh
          ./scripts/deploy/rollback.sh production auto

      - name: Send deployment notification
        if: always()
        uses: slackapi/slack-github-action@70cd7be8e40a46e8b612094aa26fbd48c5a13a8
        with:
          payload: |
            {
              "text": "Production deployment ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Production Deployment ${{ job.status }}*\nVersion: ${{ github.ref_name }}\nStrategy: ${{ needs.pre-deployment-checks.outputs.strategy }}\nActor: ${{ github.actor }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  post-deployment:
    name: Post-Deployment Tasks
    runs-on: ubuntu-latest
    needs: [deploy-staging, deploy-production]
    if: always() && (needs.deploy-staging.result == 'success' || needs.deploy-production.result == 'success')

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Create deployment record
        run: |
          echo "Recording deployment..."
          mkdir -p deployment-history
          cat > deployment-history/deployment-$(date +%Y%m%d-%H%M%S).json <<EOF
          {
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "environment": "${{ needs.pre-deployment-checks.outputs.environment }}",
            "strategy": "${{ needs.pre-deployment-checks.outputs.strategy }}",
            "version": "${{ github.ref_name }}",
            "commit": "${{ github.sha }}",
            "actor": "${{ github.actor }}",
            "status": "success"
          }
          EOF

      - name: Update deployment badge
        run: |
          echo "Updating deployment badge..."
          # Add logic to update deployment status badge

      - name: Trigger post-deployment monitoring
        run: |
          echo "Setting up extended monitoring..."
          # Add logic to enable extended monitoring for 24 hours
