name: E2E Tests

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  e2e-tests:
    name: E2E Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [20.x]
      fail-fast: false

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: noa_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6380:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@161b8d0c4739f28c4f8391fa2b2c23d8b6c4b2b2
        with:
          version: 9.11.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Start Mock AI Providers
        run: |
          cd tests/e2e/utils
          node ai-provider-mock.ts --port 8081 &
          node ai-provider-mock.ts --port 8082 &
          sleep 5

      - name: Initialize test database
        run: |
          PGPASSWORD=test_password psql -h localhost -p 5433 -U test_user -d noa_test -f tests/e2e/setup/init-db.sql

      - name: Run E2E tests
        env:
          NODE_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5433
          POSTGRES_DB: noa_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          REDIS_HOST: localhost
          REDIS_PORT: 6380
          MOCK_OPENAI_URL: http://localhost:8081
          MOCK_CLAUDE_URL: http://localhost:8082
        run: |
          pnpm test:e2e --coverage --reporter=verbose --reporter=json --reporter=html

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@65462800fd760344b1a7b4382954b84365f3d453
        with:
          name: e2e-test-results-${{ matrix.node-version }}
          path: |
            tests/e2e/reports/
            coverage/e2e/

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@5b6b21c47e7704e4e6f19b2c9d5c3b3c3c3c3c
        with:
          files: ./coverage/e2e/lcov.info
          flags: e2e
          name: e2e-coverage
          fail_ci_if_error: true

      - name: Check coverage thresholds
        run: |
          pnpm vitest run --coverage --coverage.thresholds.lines=80 --coverage.thresholds.functions=80

      - name: Comment PR with results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('tests/e2e/reports/e2e-test-results.json', 'utf8'));

            const { numTotalTests, numPassedTests, numFailedTests, success } = results;
            const emoji = success ? '✅' : '❌';

            const body = `## ${emoji} E2E Test Results

            - **Total Tests**: ${numTotalTests}
            - **Passed**: ${numPassedTests}
            - **Failed**: ${numFailedTests}
            - **Success Rate**: ${((numPassedTests / numTotalTests) * 100).toFixed(2)}%

            [View detailed report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

  e2e-load-tests:
    name: E2E Load Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 20.x

      - name: Setup pnpm
        uses: pnpm/action-setup@161b8d0c4739f28c4f8391fa2b2c23d8b6c4b2b2
        with:
          version: 9.11.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Start test environment
        run: |
          docker-compose -f tests/e2e/setup/docker-compose.test.yml up -d
          sleep 10

      - name: Run load tests
        run: |
          pnpm vitest run tests/e2e/load/ --reporter=json --reporter=html

      - name: Upload load test results
        if: always()
        uses: actions/upload-artifact@65462800fd760344b1a7b4382954b84365f3d453
        with:
          name: load-test-results
          path: tests/e2e/reports/

      - name: Cleanup
        if: always()
        run: |
          docker-compose -f tests/e2e/setup/docker-compose.test.yml down -v
