openapi: 3.0.3
info:
  title: Users API
  version: 1.0.0

paths:
  /users:
    get:
      summary: List users
      description: Get paginated list of users (admin only)
      tags:
        - Users
      security:
        - bearerAuth: []
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/PageParam'
        - $ref: '../openapi.yaml#/components/parameters/LimitParam'
        - $ref: '../openapi.yaml#/components/parameters/SortParam'
        - name: role
          in: query
          description: Filter by role
          schema:
            type: string
            enum: [admin, user, agent, viewer]
        - name: status
          in: query
          description: Filter by account status
          schema:
            type: string
            enum: [active, inactive, suspended]
        - name: search
          in: query
          description: Search by username or email
          schema:
            type: string
      responses:
        '200':
          description: Users retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                  meta:
                    $ref: '../openapi.yaml#/components/schemas/PaginationMeta'
        '401':
          $ref: '../openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../openapi.yaml#/components/responses/Forbidden'

    post:
      summary: Create user
      description: Create a new user (admin only)
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/User'
        '400':
          $ref: '../openapi.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../openapi.yaml#/components/responses/Forbidden'
        '409':
          $ref: '../openapi.yaml#/components/responses/Conflict'

  /users/{userId}:
    get:
      summary: Get user by ID
      description: Retrieve user details by user ID
      tags:
        - Users
      security:
        - bearerAuth: []
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/UserIdParam'
      responses:
        '200':
          description: User retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/User'
        '401':
          $ref: '../openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../openapi.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../openapi.yaml#/components/responses/NotFound'

    put:
      summary: Update user
      description: Update user information
      tags:
        - Users
      security:
        - bearerAuth: []
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/UserIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/User'
        '400':
          $ref: '../openapi.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../openapi.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../openapi.yaml#/components/responses/NotFound'

    delete:
      summary: Delete user
      description: Delete user account (admin only)
      tags:
        - Users
      security:
        - bearerAuth: []
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/UserIdParam'
      responses:
        '200':
          description: User deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '401':
          $ref: '../openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../openapi.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../openapi.yaml#/components/responses/NotFound'

  /users/{userId}/roles:
    get:
      summary: Get user roles
      description: Retrieve all roles assigned to user
      tags:
        - Users
      security:
        - bearerAuth: []
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/UserIdParam'
      responses:
        '200':
          description: Roles retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Role'
        '401':
          $ref: '../openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../openapi.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../openapi.yaml#/components/responses/NotFound'

    post:
      summary: Assign role to user
      description: Add role to user (admin only)
      tags:
        - Users
      security:
        - bearerAuth: []
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/UserIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - roleId
              properties:
                roleId:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Role assigned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          $ref: '../openapi.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../openapi.yaml#/components/responses/Forbidden'

    delete:
      summary: Remove role from user
      description: Remove role from user (admin only)
      tags:
        - Users
      security:
        - bearerAuth: []
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/UserIdParam'
        - name: roleId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Role removed successfully
        '401':
          $ref: '../openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../openapi.yaml#/components/responses/Forbidden'

  /users/{userId}/permissions:
    get:
      summary: Get user permissions
      description: Retrieve all permissions for user
      tags:
        - Users
      security:
        - bearerAuth: []
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/UserIdParam'
      responses:
        '200':
          description: Permissions retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      type: string
                    example:
                      - users:read
                      - users:write
                      - workflows:execute
                      - agents:spawn
        '401':
          $ref: '../openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../openapi.yaml#/components/responses/Forbidden'

  /users/me:
    get:
      summary: Get current user
      description: Retrieve authenticated user's profile
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/User'
        '401':
          $ref: '../openapi.yaml#/components/responses/Unauthorized'

    put:
      summary: Update current user
      description: Update authenticated user's profile
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/User'
        '400':
          $ref: '../openapi.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../openapi.yaml#/components/responses/Unauthorized'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        avatar:
          type: string
          format: uri
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
        status:
          type: string
          enum: [active, inactive, suspended]
        mfaEnabled:
          type: boolean
        emailVerified:
          type: boolean
        metadata:
          type: object
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        lastLoginAt:
          type: string
          format: date-time

    Role:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          enum: [admin, user, agent, viewer]
        description:
          type: string
        permissions:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time

    CreateUserRequest:
      type: object
      required:
        - email
        - username
        - password
      properties:
        email:
          type: string
          format: email
        username:
          type: string
          minLength: 3
          maxLength: 50
        password:
          type: string
          format: password
          minLength: 8
        firstName:
          type: string
        lastName:
          type: string
        roles:
          type: array
          items:
            type: string
          default: [user]
        metadata:
          type: object

    UpdateUserRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        username:
          type: string
          minLength: 3
          maxLength: 50
        firstName:
          type: string
        lastName:
          type: string
        avatar:
          type: string
          format: uri
        metadata:
          type: object
